name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: memoka_server
    env:
      VERSION: '3.2.3'
      SERVERPOD_PASSWORD_database: 'HEDBcpu2NNA1cMwC3EmK83YS-78JRpwB'
      SERVERPOD_PASSWORD_redis: 'VrcHvH3Qje8yrXsGIDWig3dxx-oNR-PX'
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7'
      - run: docker compose up --build -d
      - run: dart pub get
      - run: dart pub global activate serverpod_cli $VERSION
      - run: serverpod generate
      - run: dart test
      - if: always()
        run: docker compose down -v
